manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3 #use "main" if you want the most up to date version
      import: app/west.yml
  self:
    path: config
