on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

#Use "main" if you want the most up to date version. Also change github workflow yml file. This might break your current code.